### ISSUE TITLE
Add missing stop point for PLAs

### ISSUE THREAD

**Issue by StormeHawke** [WazeDev/WME-Place-Harmonizer#247] opened 2017-11-03 18:35 UTC
Suggestion: Rather than having a button to add a missing stop point for PLAs, why not just auto-add it if it's missing? Would save a click and two sweeps of the mouse across the screen

**Comment by mapomatic** [comment] 2017-11-06 12:44
Duplicate of #237

**Closed by mapomatic** 2017-11-06 12:44 UTC
Labels: Duplicate
